LibraryMVC/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using NuGet.Versioning;
using SoftwareDevelopment2.Data;
using SoftwareDevelopment2.Models;
using SoftwareDevelopment2.ViewModels;

namespace SoftwareDevelopment2.Controllers
{

    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BooksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {

            return _context.Books != null ?
                View(await GetBookViewModels()) :
                Problem("Entity set 'ApplicationDbContext.Book'  is null.");
        }

        // GET: Show form Books
        public async Task<IActionResult> ShowSearchForm()
        {
            return View(new SearchViewModel { });
        }

        // POST: form Books
        public async Task<IActionResult> ShowSearchResult(SearchViewModel search)
        {
            if (search.SearchPhrase == null)
                return NotFound();

            var bookViewModels = await GetBookViewModels();

            switch (search.SearchOn)
            {
                case SearchOn.Title:
                    return View("Index", bookViewModels.Where(book => book.Book.Title.ToUpper().Contains(search.SearchPhrase.ToUpper())));
                case SearchOn.Author:

                    return View("Index", bookViewModels.Where(book => book.Author.Name.ToUpper().Contains(search.SearchPhrase.ToUpper())));
                case SearchOn.Location:

                    return View("Index", bookViewModels.Where(book => book.Location.Name.ToUpper().Contains(search.SearchPhrase.ToUpper())));
            }

            return View("Index", bookViewModels);
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var bookViewModel = await GetBookViewModel(id);

            if (bookViewModel == null)
            {
                return NotFound();
            }

            return View(bookViewModel);
        }

        // [] = Decorator
        // unless you've been logged in
        [Authorize]

        // GET: Books/Create
        [Authorize(Roles = "Employee, Admin")]
        public async Task<IActionResult> Create()
        {
            var createBookViewModel = new CreateBookViewModel
            {
                Book = new Book { },
                Author = await _context.Authors.ToListAsync(),
                Location = await _context.Locations.ToListAsync(),
                AuthorChoice = new Author { },
                LocationChoice = new Models.Location { }
            };

            return View(createBookViewModel);
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Employee, Admin")]
        public async Task<IActionResult> Create([Bind("Book, AuthorChoice, LocationChoice")] CreateBookViewModel bookViewModel)
        {
            var book = bookViewModel.Book;
            if (ModelState.IsValid)
            {

                book.AuthorId = bookViewModel.AuthorChoice.Id;
                book.LocationId = bookViewModel.LocationChoice.Id;
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Edit/5
        [Authorize(Roles = "Employee, Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            var bookViewModel = await GetCreateBookViewModel(id);

            if (bookViewModel == null)
            {
                return NotFound();
            }

            return View(bookViewModel);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Employee, Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Book, AuthorChoice, LocationChoice")] CreateBookViewModel bookViewModel)
        {
            if (id != bookViewModel.Book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var book = bookViewModel.Book;
                    book.AuthorId = bookViewModel.AuthorChoice.Id;
                    book.LocationId = bookViewModel.LocationChoice.Id;
                    _context.Update(bookViewModel.Book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(bookViewModel.Book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bookViewModel);
        }

        // GET: Books/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Books == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Book'  is null.");
            }
            var book = await _context.Books.FindAsync(id);
            if (book != null)
            {
                _context.Books.Remove(book);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return (_context.Books?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private async Task<IEnumerable<BookViewModel>> GetBookViewModels()
        {
            var books = await _context.Books.ToListAsync();

            var authors = await _context.Authors.ToListAsync();
            var locations = await _context.Locations.ToListAsync();

            var bookViewModels = new List<BookViewModel>();

            //Find the correspond authors and locations for each book
            foreach (var book in books)
            {
                var author = await _context.Authors.FirstOrDefaultAsync(author => author.Id == book.AuthorId);
                var location = await _context.Locations.FirstOrDefaultAsync(location => location.Id == book.LocationId);
                bookViewModels.Add(new BookViewModel
                {
                    Book = book,
                    Author = author,
                    Location = location,
                });
            }

            return bookViewModels;
        }
        private async Task<BookViewModel?> GetBookViewModel(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return null;
            }
            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return null;
            }
            var author = await _context.Authors.FindAsync(book.AuthorId);
            var location = await _context.Locations.FindAsync(book.LocationId);
            if (author == null || location == null)
            {
                return null;
            }

            var bookViewModel = new BookViewModel
            {
                Book = book,
                Author = author,
                Location = location
            };
            return bookViewModel;
        }

        private async Task<CreateBookViewModel?> GetCreateBookViewModel(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return null;
            }
            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return null;
            }
            var author = await _context.Authors.FindAsync(book.AuthorId);
            var location = await _context.Locations.FindAsync(book.LocationId);
            if (author == null || location == null)
            {
                return null;
            }

            var bookViewModel = new CreateBookViewModel
            {
                Book = book,
                Author = await _context.Authors.ToListAsync(),
                Location = await _context.Locations.ToListAsync(),
                AuthorChoice = author,
                LocationChoice = location
            };
            return bookViewModel;
        }


    }

}

LibraryMVC/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SoftwareDevelopment2.Data;
using SoftwareDevelopment2.Models;
using SoftwareDevelopment2.ViewModels;
using System;

namespace SoftwareDevelopment2.Controllers
{
    [Authorize(Roles = "Employee, Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly ApplicationDbContext _context;

        public UsersController(UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            this.userManager = userManager;
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var users = userManager.Users;
            return View(users);
        }


        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var userRole = await _context.UserRoles.FirstOrDefaultAsync(userRole => userRole.UserId == id);
            IdentityRole? role;

            // if unable to find associated role, we assume user role
            IdentityRole defaultRole = new IdentityRole
            {
                Name = "User"
            };

            if (userRole != null)
            {
                role = await _context.Roles.FirstOrDefaultAsync(role => role.Id == userRole.RoleId);
                if (role == null)
                {
                    role = defaultRole;
                }
            }
            else
            {
                role = defaultRole;
            }

            // true if user is authorized to block account
            bool authorized =
                User.IsInRole("Admin") ||
                User.IsInRole("Employee") &&
                role.Name == "User";

            var userViewModel = new EditUserViewModel
            {
                Id = id,
                Email = user.Email,
                PasswordHash = user.PasswordHash,
                IsLocked = user.LockoutEnd > DateTime.UtcNow,
                Authorized = authorized
            };

            return View(userViewModel);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Email, PasswordHash, Id, IsLocked")] EditUserViewModel userViewModel)
        {
            if (id != userViewModel.Id)
            {
                return NotFound();
            }
            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //set input values
                    user.Email = userViewModel.Email;
                    user.UserName = user.Email;
                    user.PasswordHash = userViewModel.PasswordHash;

                    // locks or unlocks users based on input
                    if (userViewModel.IsLocked)
                    {
                        user.LockoutEnd = DateTime.UtcNow.AddYears(999);
                        user.LockoutEnabled = true;
                    }
                    else
                    {
                        user.LockoutEnd = DateTime.Now;
                        user.LockoutEnabled = false;
                    }

                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(user => user.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Users'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
            return (_context.Users?.Any(e => e.Id == id)).GetValueOrDefault();
        }

    }

}

LibraryMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SoftwareDevelopment2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SoftwareDevelopment2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="ShowSearchForm">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subscriptions" asp-action="Index">Subscriptions</a>
                        </li>
                        @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MyPage" asp-action="Index">Manager Page</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="Index">Locations</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MyPage" asp-action="MyIndex">MyPage</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LibraryMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>